import React from 'react';
import type { DevelopmentTask } from '../types';

interface DevelopmentViewProps {
  tasks: DevelopmentTask[];
  onStatusChange?: (id: string, status: DevelopmentTask['status']) => void;
}

const statuses: DevelopmentTask['status'][] = [
  'Ready',
  'In Development',
  'Blocked',
  'Code Review',
  'QA',
  'Completed',
];

export const DevelopmentView: React.FC<DevelopmentViewProps> = ({
  tasks,
  onStatusChange,
}) => {
  const counts = statuses.map((s) => ({
    status: s,
    count: tasks.filter((t) => t.status === s).length,
  }));

  return (
    <div className="max-w-[1280px] mx-auto px-8 py-8 w-full animate-in fade-in duration-200">
      <div className="mb-8">
        <h1 className="text-[32px] font-semibold text-[#191c1e] tracking-tight">
          Development Workspace
        </h1>
        <p className="text-[15px] text-[#45464d] mt-1">
          Engineering context generated by the platform — not a Jira clone.
        </p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-6 gap-3 mb-8">
        {counts.map((c) => (
          <div key={c.status} className="bg-white border border-[#c6c6cd] rounded-lg p-3 shadow-2xs">
            <div className="text-[11px] font-semibold text-[#76777d] uppercase truncate">
              {c.status}
            </div>
            <div className="text-[22px] font-semibold text-[#191c1e] mt-1">{c.count}</div>
          </div>
        ))}
      </div>

      {tasks.length === 0 ? (
        <div className="bg-white border border-[#c6c6cd] rounded-lg p-8 text-center text-[#76777d]">
          No development tasks yet.
        </div>
      ) : (
        <div className="bg-white border border-[#c6c6cd] rounded-lg overflow-hidden shadow-2xs">
          <div className="p-4 bg-[#f7f9fb] border-b border-[#c6c6cd] font-semibold text-[#191c1e]">
            Board
          </div>
          <div className="divide-y divide-[#c6c6cd]/50 text-[14px]">
            {tasks.map((task) => (
              <div
                key={task.id}
                className="p-4 flex flex-col md:flex-row md:justify-between md:items-center gap-3 hover:bg-[#f7f9fb]"
              >
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-semibold text-[#191c1e]">{task.title}</span>
                    {task.aiGenerated && (
                      <span className="text-[10px] uppercase font-semibold px-1.5 py-0.5 rounded bg-[#e1e0ff] text-[#2f2ebe]">
                        AI
                      </span>
                    )}
                  </div>
                  <div className="text-[13px] text-[#76777d]">
                    {task.project} · {task.developer} · {task.priority} priority
                    {task.requestId ? ` · ${task.requestId}` : ''}
                  </div>
                </div>
                <select
                  className="text-[13px] border border-[#c6c6cd] rounded px-2 py-1.5 bg-white"
                  value={task.status}
                  onChange={(e) =>
                    onStatusChange?.(task.id, e.target.value as DevelopmentTask['status'])
                  }
                  aria-label={`Status for ${task.title}`}
                >
                  {statuses.map((s) => (
                    <option key={s} value={s}>
                      {s}
                    </option>
                  ))}
                </select>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
